config/routes.rb
QcriScholars::Application.routes.draw do

  devise_for :users

  resources :scholars do
    post 'update_all', :on => :collection
  end

  root :to => 'scholars#index'

end

app/models/scholar.rb
class Scholar < ActiveRecord::Base
  attr_accessible :id, :name, :google_scholar_id, :dblp_author_id
  attr_accessible :citations, :hindex, :i10index, :recent_citations, :recent_hindex, :recent_i10index
  attr_accessible :current_position, :phd_from, :phd_year, :last_institution, :last_job

  has_many :scholar_venues, dependent: :destroy, order: "count desc"
  has_many :venues, through: :scholar_venues

  def scrape
    scraper = GoogleScholarScraper.new
    ret1 = scraper.get_scholar_citations(self)
    ret2 = scraper.get_dblp_info(self)
    if ret1 || ret2
      self.save
    else
      return nil
    end
  end

  def to_s
    self.name
  end

  def image_url
    "http://scholar.google.com/citations?view_op=view_photo&user=#{self.google_scholar_id}"
  end

  def self.update_all
    not_done = true
    GoogleScholarScraper.new.update_all(Scholar.all) do
      logger.debug "Updated scholars successfully"
      not_done = false
    end
    while not_done
      sleep(1)
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |scholar|
        csv << scholar.attributes.values_at(*column_names)
      end
    end
  end

  def phd
    if phd_year && phd_year > 0
      "#{phd_from} (#{phd_year})"
    else
      "#{phd_from}"
    end
  end
end

app/controllers/scholars_controller.rb
class ScholarsController < ApplicationController
  def index
    @scholars = Scholar.order("COALESCE(citations, 0) desc, name")
    respond_to do |format|
      format.html # template
      format.json { render :json => @scholars }
      format.xml { render :xml => @scholars }
      format.csv { send_data @scholars.to_csv }
      format.xls { send_data @scholars.to_csv(col_sep: "\t") } # tempalte
    end
  end

  def show
    @scholar = Scholar.find(params[:id])
  end

  def new
    @scholar = Scholar.new
  end

  def create
    @scholar = Scholar.new params[:scholar]
    create_or_update
  end

  def edit
    @scholar = Scholar.find(params[:id])
  end

  def update
    @scholar = Scholar.find(params[:id])
    if @scholar.update_attributes(params[:scholar])
      create_or_update
    else
      redirect_to edit_scholar_url, :alert => "Error saving scholar"
    end
  end

  def destroy
    @scholar = Scholar.find(params[:id])
    if @scholar.destroy
      redirect_to scholars_url, :notice => "Scholar deleted successfully"
    else
      redirect_to scholar_url(@scholar), :alert => "Error deleting scholar"
    end
  end

  def update_all
    Scholar.delay.update_all
    redirect_to scholars_url, :notice => "Scholars update all started successfully, check back in a while"
  end

  protected

  def create_or_update
    if @scholar.google_scholar_id.blank? && @scholar.dblp_author_id.blank?
      redirect_to new_scholar_url, :alert => "Both Google Scholar ID and DBLP Author Name are missing"
    elsif @scholar.scrape
      redirect_to scholar_url(@scholar), :notice => "Scholar fetched successfully"
    else
      redirect_to new_scholar_url, :alert => "Error finding scholar"
    end
  end
end

app/helpers/scholars_helper.rb
module ScholarsHelper
  def since(scholar)
    "Since #{scholar.scraped_at.year - 5}" if scholar.scraped_at && scholar.citations
  end
end

app/views/scholars/_form.html.erb
<%= form_for(@scholar) do |f| %>
  <p>
    <%= f.label :google_scholar_key %>:
    <%= f.text_field :google_scholar_id, :size => 30 %>
  </p>
  <p>
    <%= f.label :dblp_author_name %>:
    <%= f.text_field :dblp_author_id, :size => 30 %>
  </p>
  <p>
    <%= f.label :current_position %>:
    <%= f.text_field :current_position %>
  </p>
  <p>
    <%= f.label :phd_from %>:
    <%= f.text_field :phd_from %>
  </p>
  <p>
    <%= f.label :phd_year %>:
    <%= f.text_field :phd_year %>
  </p>
  <p>
    <%= f.label :last_institution %>:
    <%= f.text_field :last_institution %>
  </p>
  <p>
    <%= f.label :last_job %>:
    <%= f.text_field :last_job %>
  </p>
  <%= f.submit "Save & Search" %>
<% end %>

app/views/scholars/_header_footer.html.erb
<p>
<%= link_to 'New scholar', new_scholar_path %>
|
<%= link_to 'Update all', update_all_scholars_path, method: :post %>
</p>

<p>
  Download:
  <%= link_to "XML", scholars_path(format: "xml") %> |
  <%= link_to "JSON", scholars_path(format: "json") %> |
  <%= link_to "CSV", scholars_path(format: "csv") %> |
  <%= link_to "Excel", scholars_path(format: "xls") %>
</p>

app/views/scholars/edit.html.erb
<h1>Update Scholar: <%= @scholar.name %></h1>

<%= render "form" %>

<p><%= link_to 'List all scholars', scholars_path %></p>

app/views/scholars/index.html.erb
<h1>Listing Scholars</h1>

<%= render partial: 'header_footer' %>

<table border=1 cellspacing="0" cellpadding="5">
  <tbody>
    <tr style="font-weight: bold; text-align: center; background-color: silver">
      <td>Name</td>
      
      <td>Current Position</td>
      <td>PhD</td>
      <td>Last Institution</td>
      <td>Last Job</td>
      
      <td>Citations</td>
      <td>H-index</td>
      <td>I10-index</td>
      <td>Recent Citations</td>
      <td>Recent H-index</td>
      <td>Recent I10-index</td>
      
      <td>Top Venue I</td>
      <td>Top Venue II</td>
      <td>Top Venue III</td>
      <td>Last Updated</td>
    </tr>

<% @scholars.each do |scholar| %>
    <tr>
      <td><%= link_to scholar, scholar_path(scholar) %></td>

      <td><%= scholar.current_position %></td>
      <td><%= scholar.phd %></td>
      <td><%= scholar.last_institution %></td>
      <td><%= scholar.last_job %></td>

      <td><%= scholar.citations %></td>
      <td><%= scholar.hindex %></td>
      <td><%= scholar.i10index %></td>
      <td><%= scholar.recent_citations %> <i><sub><%= since(scholar) %></sub></i></td>
      <td><%= scholar.recent_hindex %> <i><sub><%= since(scholar) %></sub></i></td>
      <td><%= scholar.recent_i10index %> <i><sub><%= since(scholar) %></sub></i></td>
      
      <td><%= scholar.scholar_venues[0] %></td>
      <td><%= scholar.scholar_venues[1] %></td>
      <td><%= scholar.scholar_venues[2] %></td>
      <td><%= scholar.scraped_at %></td>
    </tr>
<% end %>

  </tbody>
</table>

<%= render partial: 'header_footer' %>

app/views/scholars/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Citations</Data></Cell>
        <Cell><Data ss:Type="String">H-index</Data></Cell>
        <Cell><Data ss:Type="String">I10-index</Data></Cell>
        <Cell><Data ss:Type="String">Recent Citations</Data></Cell>
        <Cell><Data ss:Type="String">Recent H-index</Data></Cell>
        <Cell><Data ss:Type="String">Recent I10-index</Data></Cell>
        <Cell><Data ss:Type="String">Top Venue I</Data></Cell>
        <Cell><Data ss:Type="String">Top Venue II</Data></Cell>
        <Cell><Data ss:Type="String">Top Venue III</Data></Cell>
        <Cell><Data ss:Type="String">Last Updated</Data></Cell>
      </Row>
    <% @scholars.each do |scholar| %>
      <Row>
        <Cell><Data ss:Type="String"><%= scholar.name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= scholar.citations %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= scholar.hindex %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= scholar.i10index %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= scholar.recent_citations %></sub></Data></Cell>
        <Cell><Data ss:Type="Number"><%= scholar.recent_hindex %></sub></Data></Cell>
        <Cell><Data ss:Type="Number"><%= scholar.recent_i10index %></sub></Data></Cell>
        <Cell><Data ss:Type="String"><%= scholar.scholar_venues[0] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= scholar.scholar_venues[1] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= scholar.scholar_venues[2] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= scholar.scraped_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/scholars/new.html.erb
<h1>New Scholar</h1>

<%= render "form" %>

<p><%= link_to 'List all scholars', scholars_path %></p>

app/views/scholars/show.html.erb
<h1>
  Scholar: <%= @scholar.name %>
  <span style="font-size: 50%">
    <%= link_to 'Update', edit_scholar_path %>
  </span>
  <span style="font-size: 50%">
    <%= link_to 'Delete', @scholar, method: 'delete', data: { confirm: 'Are you sure you want to delete this scholar?' } %>
  </span>
</h1>
<p>
  <b>Last updated:</b> <%= @scholar.scraped_at %>
</p>

<p>
  <b>Current Position:</b> <%= @scholar.current_position %>
</p>
<p>
  <b>PhD:</b> <%= @scholar.phd %>
</p>
<p>
  <b>Last Institution:</b> <%= @scholar.last_institution %>
</p>
<p>
  <b>Last Job:</b> <%= @scholar.last_job %>
</p>

<p>
  <img src="<%= @scholar.image_url %>" />
</p>

<h2>
  <%= link_to "Google Scholar Citations", "http://scholar.google.com/citations?user=#{@scholar.google_scholar_id}&hl=en" %>
</h2>

<p>
<table border=1 cellspacing="0" cellpadding="5">
  <tbody>
    <tr>
      <td>&nbsp;</td>
      <td>All</td>
      <td><%= since(@scholar) %></td>
    </tr>
    <tr>
      <td>Citations</td>
      <td><%= @scholar.citations %></td>
      <td><%= @scholar.recent_citations %></td>
    </tr>
    <tr>
      <td>h-index</td>
      <td><%= @scholar.hindex %></td>
      <td><%= @scholar.recent_hindex %></td>
    </tr>
    <tr>
      <td>i10-index</td>
      <td><%= @scholar.i10index %></td>
      <td><%= @scholar.recent_i10index %></td>
    </tr>
  </tbody>
</table>
</p>

<% if !@scholar.dblp_author_id.blank? && @scholar.scholar_venues.length > 0 %>

<h2>
<%= link_to "DBLP Venues", "http://www.dblp.org/search/index.php#query=author:#{@scholar.dblp_author_id}" %>
</h2>

<ul>
<% @scholar.scholar_venues.each do |scholar_venue| %>
  <li>
    <%= scholar_venue %>
  </li>
<% end %>
</ul>

<% end %>

<p>
  <%= link_to 'List all scholars', scholars_path %>
</p>